import { useState, useEffect } from "react";
import { AppLayout } from "@/components/AppLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Save, FileText, Calculator, Users } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate } from "react-router-dom";

type KopTemplate = {
  id: string;
  nama_instansi: string;
  nama_unit_kerja: string | null;
};

type PejabatTemplate = {
  id: string;
  jabatan: string;
  nama: string;
  nip: string | null;
};

const InputKegiatan = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [kopTemplates, setKopTemplates] = useState<KopTemplate[]>([]);
  const [pejabatTemplates, setPejabatTemplates] = useState<PejabatTemplate[]>([]);

  // Form state
  const [namaKegiatan, setNamaKegiatan] = useState("");
  const [kodeMak, setKodeMak] = useState("");
  const [tanggal, setTanggal] = useState("");
  const [lokasi, setLokasi] = useState("");
  const [uraian, setUraian] = useState("");
  const [jenisKegiatan, setJenisKegiatan] = useState("");
  const [nilaiBruto, setNilaiBruto] = useState("");
  const [kopId, setKopId] = useState("");
  const [ppkNama, setPpkNama] = useState("");
  const [ppkNip, setPpkNip] = useState("");
  const [bendaharaNama, setBendaharaNama] = useState("");
  const [bendaharaNip, setBendaharaNip] = useState("");
  const [pptkNama, setPptkNama] = useState("");
  const [pptkNip, setPptkNip] = useState("");

  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    const [kopRes, pejabatRes] = await Promise.all([
      supabase.from("kop_templates").select("id, nama_instansi, nama_unit_kerja").eq("is_active", true),
      supabase.from("pejabat_templates").select("*").eq("is_active", true),
    ]);
    if (kopRes.data) setKopTemplates(kopRes.data);
    if (pejabatRes.data) setPejabatTemplates(pejabatRes.data);
  };

  const fillPejabat = (jabatan: string, setNama: (v: string) => void, setNip: (v: string) => void) => {
    const p = pejabatTemplates.find((t) => t.jabatan.toLowerCase() === jabatan.toLowerCase());
    if (p) {
      setNama(p.nama);
      setNip(p.nip || "");
    }
  };

  // Tax calc
  const pphRate = jenisKegiatan === "honor" ? 0.05 : jenisKegiatan === "pengadaan_barang" ? 0.015 : jenisKegiatan === "jasa" ? 0.02 : 0;
  const ppnRate = ["pengadaan_barang", "jasa"].includes(jenisKegiatan) ? 0.11 : 0;
  const pphJenis = jenisKegiatan === "honor" ? "PPh 21" : jenisKegiatan === "pengadaan_barang" ? "PPh 22" : jenisKegiatan === "jasa" ? "PPh 23" : "";
  const bruto = parseFloat(nilaiBruto) || 0;
  const pph = bruto * pphRate;
  const ppn = bruto * ppnRate;
  const netto = bruto - pph;

  const formatRp = (n: number) =>
    new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(n);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!namaKegiatan || !tanggal || !jenisKegiatan) {
      toast.error("Nama kegiatan, tanggal, dan jenis belanja wajib diisi");
      return;
    }

    setLoading(true);
    const { error } = await supabase.from("kegiatan").insert({
      nomor_spj: "", // auto-generated by trigger
      nama_kegiatan: namaKegiatan,
      kode_mak: kodeMak || null,
      tanggal_kegiatan: tanggal,
      lokasi: lokasi || null,
      uraian: uraian || null,
      jenis_belanja: jenisKegiatan,
      nilai_bruto: bruto,
      pph_jenis: pphJenis || null,
      pph_rate: pphRate,
      pph_nominal: pph,
      ppn_rate: ppnRate,
      ppn_nominal: ppn,
      nilai_netto: netto,
      ppk_nama: ppkNama || null,
      ppk_nip: ppkNip || null,
      bendahara_nama: bendaharaNama || null,
      bendahara_nip: bendaharaNip || null,
      pptk_nama: pptkNama || null,
      pptk_nip: pptkNip || null,
      kop_template_id: kopId || null,
      status: "draft",
    });

    setLoading(false);
    if (error) {
      toast.error("Gagal menyimpan: " + error.message);
    } else {
      toast.success("Kegiatan berhasil disimpan sebagai Draft");
      navigate("/spj");
    }
  };

  return (
    <AppLayout>
      <div className="space-y-6 animate-fade-in">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Input Kegiatan Baru</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Satu kali input, sistem otomatis menghasilkan dokumen pendukung
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Main Form */}
            <div className="lg:col-span-2 space-y-4">
              {/* KOP Template Selection */}
              <Card className="border shadow-sm">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm font-semibold flex items-center gap-2">
                    <FileText className="w-4 h-4" />
                    Template KOP Surat
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium">Pilih KOP Instansi</Label>
                    <Select value={kopId} onValueChange={setKopId}>
                      <SelectTrigger>
                        <SelectValue placeholder={kopTemplates.length > 0 ? "Pilih template KOP" : "Belum ada template KOP — buat di Pengaturan"} />
                      </SelectTrigger>
                      <SelectContent>
                        {kopTemplates.map((kop) => (
                          <SelectItem key={kop.id} value={kop.id}>
                            {kop.nama_instansi} {kop.nama_unit_kerja ? `— ${kop.nama_unit_kerja}` : ""}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {kopTemplates.length === 0 && (
                      <p className="text-xs text-muted-foreground">
                        Buat template KOP terlebih dahulu di menu{" "}
                        <a href="/pengaturan" className="text-accent underline">Pengaturan</a>
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>

              <Card className="border shadow-sm">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm font-semibold flex items-center gap-2">
                    <FileText className="w-4 h-4" />
                    Informasi Kegiatan
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Nama Kegiatan *</Label>
                      <Input
                        placeholder="Contoh: Workshop Peningkatan SDM"
                        value={namaKegiatan}
                        onChange={(e) => setNamaKegiatan(e.target.value)}
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Kode MAK</Label>
                      <Input
                        placeholder="5211.001.051.A.524111"
                        className="font-mono"
                        value={kodeMak}
                        onChange={(e) => setKodeMak(e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Tanggal Kegiatan *</Label>
                      <Input type="date" value={tanggal} onChange={(e) => setTanggal(e.target.value)} />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Lokasi</Label>
                      <Input
                        placeholder="Ruang Rapat Lt.3 Gedung A"
                        value={lokasi}
                        onChange={(e) => setLokasi(e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium">Uraian Kegiatan</Label>
                    <Textarea
                      placeholder="Jelaskan secara singkat tujuan dan uraian kegiatan..."
                      rows={3}
                      value={uraian}
                      onChange={(e) => setUraian(e.target.value)}
                    />
                  </div>

                  <Separator />

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Jenis Belanja *</Label>
                      <Select value={jenisKegiatan} onValueChange={setJenisKegiatan}>
                        <SelectTrigger>
                          <SelectValue placeholder="Pilih jenis belanja" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="honor">Honor Narasumber/Panitia</SelectItem>
                          <SelectItem value="pengadaan_barang">Pengadaan Barang</SelectItem>
                          <SelectItem value="jasa">Belanja Jasa</SelectItem>
                          <SelectItem value="perjalanan">Perjalanan Dinas</SelectItem>
                          <SelectItem value="operasional">Operasional Kantor</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Nilai Bruto (Rp)</Label>
                      <Input
                        type="number"
                        placeholder="0"
                        value={nilaiBruto}
                        onChange={(e) => setNilaiBruto(e.target.value)}
                        className="font-mono"
                      />
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Pejabat Section */}
              <Card className="border shadow-sm">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm font-semibold flex items-center gap-2">
                    <Users className="w-4 h-4" />
                    Pejabat Penandatangan
                    {pejabatTemplates.length > 0 && (
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        className="ml-auto text-xs h-7"
                        onClick={() => {
                          fillPejabat("PPK", setPpkNama, setPpkNip);
                          fillPejabat("Bendahara", setBendaharaNama, setBendaharaNip);
                          fillPejabat("PPTK", setPptkNama, setPptkNip);
                          toast.info("Data pejabat diisi dari template");
                        }}
                      >
                        Isi dari Template
                      </Button>
                    )}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">PPK (Nama)</Label>
                      <Input placeholder="Nama PPK" value={ppkNama} onChange={(e) => setPpkNama(e.target.value)} />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">PPK (NIP)</Label>
                      <Input placeholder="NIP" className="font-mono" value={ppkNip} onChange={(e) => setPpkNip(e.target.value)} />
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Bendahara (Nama)</Label>
                      <Input placeholder="Nama Bendahara" value={bendaharaNama} onChange={(e) => setBendaharaNama(e.target.value)} />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">Bendahara (NIP)</Label>
                      <Input placeholder="NIP" className="font-mono" value={bendaharaNip} onChange={(e) => setBendaharaNip(e.target.value)} />
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">PPTK (Nama)</Label>
                      <Input placeholder="Nama PPTK" value={pptkNama} onChange={(e) => setPptkNama(e.target.value)} />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs font-medium">PPTK (NIP)</Label>
                      <Input placeholder="NIP" className="font-mono" value={pptkNip} onChange={(e) => setPptkNip(e.target.value)} />
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Side Panel */}
            <div className="space-y-4">
              <Card className="border shadow-sm">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm font-semibold flex items-center gap-2">
                    <Calculator className="w-4 h-4" />
                    Perhitungan Pajak
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Nilai Bruto</span>
                    <span className="font-mono font-medium">{formatRp(bruto)}</span>
                  </div>
                  {pphRate > 0 && (
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">
                        {pphJenis} ({(pphRate * 100).toFixed(1)}%)
                      </span>
                      <span className="font-mono text-destructive">-{formatRp(pph)}</span>
                    </div>
                  )}
                  {ppnRate > 0 && (
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">PPN (11%)</span>
                      <span className="font-mono text-info">{formatRp(ppn)}</span>
                    </div>
                  )}
                  <Separator />
                  <div className="flex justify-between text-sm font-bold">
                    <span>Nilai Netto</span>
                    <span className="font-mono">{formatRp(netto)}</span>
                  </div>
                </CardContent>
              </Card>

              <Card className="border shadow-sm">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm font-semibold">Dokumen Otomatis</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground mb-3">
                    Dokumen berikut akan disiapkan secara otomatis:
                  </p>
                  <ul className="space-y-2 text-xs">
                    {["Surat Undangan", "Daftar Hadir", "Notulen Rapat", "SPTB", "Kwitansi", "SPD"].map((doc) => (
                      <li key={doc} className="flex items-center gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-accent" />
                        <span className="text-muted-foreground">{doc}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>

              <div className="flex flex-col gap-2">
                <Button type="submit" className="w-full" disabled={loading}>
                  <Save className="w-4 h-4 mr-2" />
                  {loading ? "Menyimpan..." : "Simpan Draft"}
                </Button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </AppLayout>
  );
};

export default InputKegiatan;
